
export const MOVIE_SHOWING      = 'MOVIE_SHOWING'
export const MOVIE_COMING_SOON  = 'MOVIE_COMING_SOON'
export const MOVIE_NEW_MOVIES   = 'MOVIE_NEW_MOVIES'
export const COM_SUBJECT_DETAIL = 'COM_SUBJECT_DETAIL'